// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Primitives.proto

package br.eti.fml.implementations;

public final class Primitives {
  private Primitives() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LongType extends
      com.google.protobuf.GeneratedMessage {
    // Use LongType.newBuilder() to construct.
    private LongType() {
      initFields();
    }
    private LongType(boolean noInit) {}
    
    private static final LongType defaultInstance;
    public static LongType getDefaultInstance() {
      return defaultInstance;
    }
    
    public LongType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.eti.fml.implementations.Primitives.internal_static_primitives_LongType_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.eti.fml.implementations.Primitives.internal_static_primitives_LongType_fieldAccessorTable;
    }
    
    // required int64 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private long value_ = 0L;
    public boolean hasValue() { return hasValue; }
    public long getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasValue()) {
        output.writeInt64(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.eti.fml.implementations.Primitives.LongType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.LongType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.eti.fml.implementations.Primitives.LongType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private br.eti.fml.implementations.Primitives.LongType result;
      
      // Construct using br.eti.fml.implementations.Primitives.LongType.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new br.eti.fml.implementations.Primitives.LongType();
        return builder;
      }
      
      protected br.eti.fml.implementations.Primitives.LongType internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new br.eti.fml.implementations.Primitives.LongType();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.eti.fml.implementations.Primitives.LongType.getDescriptor();
      }
      
      public br.eti.fml.implementations.Primitives.LongType getDefaultInstanceForType() {
        return br.eti.fml.implementations.Primitives.LongType.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public br.eti.fml.implementations.Primitives.LongType build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private br.eti.fml.implementations.Primitives.LongType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public br.eti.fml.implementations.Primitives.LongType buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        br.eti.fml.implementations.Primitives.LongType returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.eti.fml.implementations.Primitives.LongType) {
          return mergeFrom((br.eti.fml.implementations.Primitives.LongType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(br.eti.fml.implementations.Primitives.LongType other) {
        if (other == br.eti.fml.implementations.Primitives.LongType.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setValue(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public long getValue() {
        return result.getValue();
      }
      public Builder setValue(long value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:primitives.LongType)
    }
    
    static {
      defaultInstance = new LongType(true);
      br.eti.fml.implementations.Primitives.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:primitives.LongType)
  }
  
  public static final class BooleanType extends
      com.google.protobuf.GeneratedMessage {
    // Use BooleanType.newBuilder() to construct.
    private BooleanType() {
      initFields();
    }
    private BooleanType(boolean noInit) {}
    
    private static final BooleanType defaultInstance;
    public static BooleanType getDefaultInstance() {
      return defaultInstance;
    }
    
    public BooleanType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.eti.fml.implementations.Primitives.internal_static_primitives_BooleanType_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.eti.fml.implementations.Primitives.internal_static_primitives_BooleanType_fieldAccessorTable;
    }
    
    // required bool value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean hasValue;
    private boolean value_ = false;
    public boolean hasValue() { return hasValue; }
    public boolean getValue() { return value_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasValue()) {
        output.writeBool(1, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static br.eti.fml.implementations.Primitives.BooleanType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.eti.fml.implementations.Primitives.BooleanType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private br.eti.fml.implementations.Primitives.BooleanType result;
      
      // Construct using br.eti.fml.implementations.Primitives.BooleanType.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new br.eti.fml.implementations.Primitives.BooleanType();
        return builder;
      }
      
      protected br.eti.fml.implementations.Primitives.BooleanType internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new br.eti.fml.implementations.Primitives.BooleanType();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.eti.fml.implementations.Primitives.BooleanType.getDescriptor();
      }
      
      public br.eti.fml.implementations.Primitives.BooleanType getDefaultInstanceForType() {
        return br.eti.fml.implementations.Primitives.BooleanType.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public br.eti.fml.implementations.Primitives.BooleanType build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private br.eti.fml.implementations.Primitives.BooleanType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public br.eti.fml.implementations.Primitives.BooleanType buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        br.eti.fml.implementations.Primitives.BooleanType returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.eti.fml.implementations.Primitives.BooleanType) {
          return mergeFrom((br.eti.fml.implementations.Primitives.BooleanType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(br.eti.fml.implementations.Primitives.BooleanType other) {
        if (other == br.eti.fml.implementations.Primitives.BooleanType.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setValue(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required bool value = 1;
      public boolean hasValue() {
        return result.hasValue();
      }
      public boolean getValue() {
        return result.getValue();
      }
      public Builder setValue(boolean value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:primitives.BooleanType)
    }
    
    static {
      defaultInstance = new BooleanType(true);
      br.eti.fml.implementations.Primitives.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:primitives.BooleanType)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_primitives_LongType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_primitives_LongType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_primitives_BooleanType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_primitives_BooleanType_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Primitives.proto\022\nprimitives\"\031\n\010LongTy" +
      "pe\022\r\n\005value\030\001 \002(\003\"\034\n\013BooleanType\022\r\n\005valu" +
      "e\030\001 \002(\010B(\n\032br.eti.fml.implementationsB\nP" +
      "rimitives"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_primitives_LongType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_primitives_LongType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_primitives_LongType_descriptor,
              new java.lang.String[] { "Value", },
              br.eti.fml.implementations.Primitives.LongType.class,
              br.eti.fml.implementations.Primitives.LongType.Builder.class);
          internal_static_primitives_BooleanType_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_primitives_BooleanType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_primitives_BooleanType_descriptor,
              new java.lang.String[] { "Value", },
              br.eti.fml.implementations.Primitives.BooleanType.class,
              br.eti.fml.implementations.Primitives.BooleanType.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
